version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      DATABAS_URL: postgresql://admin:admin@db/users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    volumes:
      - ./support_backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@db/users"
    depends_on:
      - db

volumes:
  postgres_data:
