"""Auto-generated migration

Revision ID: 052391a27282
Revises: fa0d855590d2
Create Date: 2025-06-25 19:08:28.581124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052391a27282'
down_revision = 'fa0d855590d2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
