"""Auto-generated migration

Revision ID: 0b33392b6e70
Revises: fb0a4f2c3f63
Create Date: 2025-06-19 07:38:25.055607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b33392b6e70'
down_revision = 'fb0a4f2c3f63'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
