"""Auto-generated migration

Revision ID: 0e5b0cae2322
Revises: bf0565af6b67
Create Date: 2025-06-25 16:35:31.451492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e5b0cae2322'
down_revision = 'bf0565af6b67'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'created_at')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.drop_column('profiles', 'created_at')
    op.alter_column('user_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('user_user_roles_user_id_fkey'), 'user_user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_user_roles_role_id_fkey'), 'user_user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_user_roles', 'user_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_user_roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_user_roles_role_id_fkey'), 'user_user_roles', 'user_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_user_roles_user_id_fkey'), 'user_user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('profiles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
