"""Auto-generated migration

Revision ID: 0f494b1deb1f
Revises: f8f5bc62f2db
Create Date: 2025-06-25 19:05:04.594301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f494b1deb1f'
down_revision = 'f8f5bc62f2db'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
