"""Auto-generated migration

Revision ID: 116b7e7d94a8
Revises: 56f3645af9f8
Create Date: 2025-07-01 14:41:01.377692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116b7e7d94a8'
down_revision = '56f3645af9f8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
