"""Auto-generated migration

Revision ID: 128238e14da4
Revises: b981bff40901
Create Date: 2025-06-19 07:29:21.125436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128238e14da4'
down_revision = 'b981bff40901'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
