"""Auto-generated migration

Revision ID: 1729a48c8369
Revises: 6641cbb4093d
Create Date: 2025-06-28 19:00:24.625511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1729a48c8369'
down_revision = '6641cbb4093d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
