"""Auto-generated migration

Revision ID: 18f6caf1f79d
Revises: 1729a48c8369
Create Date: 2025-06-28 19:14:46.811110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f6caf1f79d'
down_revision = '1729a48c8369'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
