"""Auto-generated migration

Revision ID: 2058bff79179
Revises: b8b5eb3e95bd
Create Date: 2025-06-28 20:03:12.855314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2058bff79179'
down_revision = 'b8b5eb3e95bd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
