"""Auto-generated migration

Revision ID: 20ae3db3769e
Revises: 269815025f49
Create Date: 2025-07-01 14:20:24.310375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ae3db3769e'
down_revision = '269815025f49'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
