"""Auto-generated migration

Revision ID: 269815025f49
Revises: b65ec826a80e
Create Date: 2025-07-01 14:13:16.261223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269815025f49'
down_revision = 'b65ec826a80e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
