"""Auto-generated migration

Revision ID: 316ae424ad11
Revises: 45a7531f8dd7
Create Date: 2025-07-01 14:30:57.751470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316ae424ad11'
down_revision = '45a7531f8dd7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
