"""Auto-generated migration

Revision ID: 341d94d59a77
Revises: 8769b56a00e3
Create Date: 2025-06-28 20:42:08.910388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341d94d59a77'
down_revision = '8769b56a00e3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
