"""Auto-generated migration

Revision ID: 395a9d22da5a
Revises: d9d9150f5fcb
Create Date: 2025-06-28 20:06:25.106563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395a9d22da5a'
down_revision = 'd9d9150f5fcb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
