"""Auto-generated migration

Revision ID: 4158d2e71638
Revises: 052391a27282
Create Date: 2025-06-25 19:11:59.237166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4158d2e71638'
down_revision = '052391a27282'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
