"""Auto-generated migration

Revision ID: 43ac68cb9d54
Revises: 0b33392b6e70
Create Date: 2025-06-19 07:46:04.366467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ac68cb9d54'
down_revision = '0b33392b6e70'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
