"""Auto-generated migration

Revision ID: 45a7531f8dd7
Revises: 50367c445b07
Create Date: 2025-07-01 14:26:47.349780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7531f8dd7'
down_revision = '50367c445b07'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
