"""Auto-generated migration

Revision ID: 4c58948a8a92
Revises: 68a413e0b39d
Create Date: 2025-06-28 20:17:04.750161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c58948a8a92'
down_revision = '68a413e0b39d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
