"""Auto-generated migration

Revision ID: 50367c445b07
Revises: b1b53970a28d
Create Date: 2025-07-01 14:24:36.652883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50367c445b07'
down_revision = 'b1b53970a28d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
