"""Auto-generated migration

Revision ID: 56f3645af9f8
Revises: 316ae424ad11
Create Date: 2025-07-01 14:34:24.614030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f3645af9f8'
down_revision = '316ae424ad11'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
