"""Auto-generated migration

Revision ID: 6641cbb4093d
Revises: 926061f13dcc
Create Date: 2025-06-28 18:06:44.163827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6641cbb4093d'
down_revision = '926061f13dcc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
