"""Auto-generated migration

Revision ID: 68a413e0b39d
Revises: fe7c090774f0
Create Date: 2025-06-28 20:12:23.971396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a413e0b39d'
down_revision = 'fe7c090774f0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
