"""Auto-generated migration

Revision ID: 6a298e120591
Revises: 0e5b0cae2322
Create Date: 2025-06-25 17:35:15.116377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a298e120591'
down_revision = '0e5b0cae2322'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
