"""Auto-generated migration

Revision ID: 6ca907cbfd91
Revises: 116b7e7d94a8
Create Date: 2025-07-01 14:41:38.489963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca907cbfd91'
down_revision = '116b7e7d94a8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
