"""Auto-generated migration

Revision ID: 8769b56a00e3
Revises: 97d58a6699c6
Create Date: 2025-06-28 20:41:31.000596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8769b56a00e3'
down_revision = '97d58a6699c6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
