"""Auto-generated migration

Revision ID: 87df9916cc1f
Revises: 4158d2e71638
Create Date: 2025-06-28 17:58:18.623902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87df9916cc1f'
down_revision = '4158d2e71638'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
