"""Auto-generated migration

Revision ID: 88a66a54b69e
Revises: 0b12e8270428
Create Date: 2025-06-28 20:29:29.634831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a66a54b69e'
down_revision = '0b12e8270428'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
