"""Auto-generated migration

Revision ID: 926061f13dcc
Revises: 87df9916cc1f
Create Date: 2025-06-28 17:58:34.915352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926061f13dcc'
down_revision = '87df9916cc1f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
