"""Auto-generated migration

Revision ID: 97d58a6699c6
Revises: e0a6bbb21668
Create Date: 2025-06-28 20:39:25.218451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d58a6699c6'
down_revision = 'e0a6bbb21668'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
