"""Auto-generated migration

Revision ID: a6da141010f7
Revises: 6ca907cbfd91
Create Date: 2025-07-01 14:43:38.865671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6da141010f7'
down_revision = '6ca907cbfd91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
