"""Auto-generated migration

Revision ID: b1b53970a28d
Revises: 20ae3db3769e
Create Date: 2025-07-01 14:22:21.125506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b53970a28d'
down_revision = '20ae3db3769e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
