"""Auto-generated migration

Revision ID: b4965d51c19d
Revises: 128238e14da4
Create Date: 2025-06-19 07:33:41.253564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4965d51c19d'
down_revision = '128238e14da4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
