"""Auto-generated migration

Revision ID: b65ec826a80e
Revises: dce26d42108c
Create Date: 2025-07-01 14:12:49.845485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65ec826a80e'
down_revision = 'dce26d42108c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
