"""Auto-generated migration

Revision ID: b8b5eb3e95bd
Revises: 18f6caf1f79d
Create Date: 2025-06-28 20:01:51.500649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b5eb3e95bd'
down_revision = '18f6caf1f79d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
