"""Auto-generated migration

Revision ID: d9bd11751f5e
Revises: b4965d51c19d
Create Date: 2025-06-19 07:38:06.472760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bd11751f5e'
down_revision = 'b4965d51c19d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
