"""Auto-generated migration

Revision ID: d9d9150f5fcb
Revises: 2058bff79179
Create Date: 2025-06-28 20:04:27.906115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d9150f5fcb'
down_revision = '2058bff79179'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
