"""Auto-generated migration

Revision ID: dce26d42108c
Revises: 341d94d59a77
Create Date: 2025-07-01 14:12:40.231230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce26d42108c'
down_revision = '341d94d59a77'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
