"""Auto-generated migration

Revision ID: e0a6bbb21668
Revises: 88a66a54b69e
Create Date: 2025-06-28 20:33:33.901927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a6bbb21668'
down_revision = '88a66a54b69e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
