"""Auto-generated migration

Revision ID: f1c7b9f88338
Revises: 43ac68cb9d54
Create Date: 2025-06-19 07:46:15.916797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c7b9f88338'
down_revision = '43ac68cb9d54'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
