"""Auto-generated migration

Revision ID: f8f5bc62f2db
Revises: 6a298e120591
Create Date: 2025-06-25 17:45:52.566567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f5bc62f2db'
down_revision = '6a298e120591'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
