"""Auto-generated migration

Revision ID: fa0d855590d2
Revises: 0f494b1deb1f
Create Date: 2025-06-25 19:08:14.325100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0d855590d2'
down_revision = '0f494b1deb1f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
