"""Auto-generated migration

Revision ID: fb0a4f2c3f63
Revises: d9bd11751f5e
Create Date: 2025-06-19 07:38:18.004272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0a4f2c3f63'
down_revision = 'd9bd11751f5e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
