"""Auto-generated migration

Revision ID: fe7c090774f0
Revises: 395a9d22da5a
Create Date: 2025-06-28 20:08:29.647860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7c090774f0'
down_revision = '395a9d22da5a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
